# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = phone_book.out
SRCS = PhoneBook.cpp Contact.cpp

include ../template.mk

PhoneBook.cpp: PhoneBook.hpp Contact.hpp
Contact.cpp: Contact.hpp
