# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = tests.out
SRCS = Account.cpp tests.cpp

include ../template.mk

Account.cpp: Account.hpp
tests.cpp: Account.hpp
